### ISSUE TITLE
How do we get started with ATK 9.2?

### ISSUE THREAD

**Issue by jgarifuna** [Sintattica/atk#62]
Thank you so much for the release of ATK 9.2!!!
The addition of AdminLte is a much welcomed component to ATK.
I migrated all my modules last year from ATK 6 to ATK 9.0 and it was a very involved but worthy effort.

I'm wondering about the process to upgrade from 9.0 to 9.2.
I looked at the **CHANGES** files of both and they're identical. Github shows that there are over 700,000 lines added to the latest release. When I downloaded the files from [](https://github.com/Sintattica/atk/releases/tag/v9.2), I see the "src" directory. 

Is the "**src**" directory shown in ATK 9.2 expected to be a straight replacement for "**vendor/sintattica/atk/src**" of ATK 9.0?

**Comment by NGjata** [comment]
Hi, 

Thanks for being interested in our project. 
This version is meant as a replacement of the former release (atk v9.1), but todays release is a pre-release and we’re still making some changes. This pre-release is meant as a graphical update with an integration of AdminLte framework, if you have an existing project you just have to update the dependency but we would suggest waiting a little bit more as unfortunately, this version is not yet production ready. We are still considering some changes on the php version because we would like to keep supporting php7.2 so in the next days probably we’ll release a compatible version, some tutorials and a skeleton so you can set up a project as smoothly as possible. 

If you are starting a new project you should create a skeleton project and put atk-framework as a dependency (but please remember some things may not work as expected, we’re still working on this pre-release).

If you still just want to give it a try then you have to update composer dependencies to this version and you have the new style. 



Best regards, 

Sintattica team
NG

**Comment by jgarifuna** [comment]
Thank you for your prompt response.

**Comment by jgarifuna** [comment]
Hi,

I was wondering if any progress has been made in making ATK 9.2 closer to
being production ready.

kind regards,

Jorge Garifuna

**Comment by NGjata** [comment]
Hi,
We just published the v9.2.1 and it contains fixes for all the problems we have found so far. 
We’re using this version on our systems and we're fixing on the go every problem that’s coming up. We still recommend testing this release in development before using it in production as ATK doesn’t have a test coverage and that’s why we cannot guarantee that we’ve covered everything, anyway we have tried to manually test all commonly used parts and right now we don’t have any active bugs. 
Feel free to try it and to report any bugs you may find. 


Kind regards,
NG
Team Sintattica

**Comment by jgarifuna** [comment]
Thanks a million Menso! That's a very welcoming news!

kind regards,

Jorge Garifuna

**Comment by AJITPRASADDIXIT** [comment]
I am old experienced user of ATK 6 and want to start working with atk-9.2.1
Can I use atk-9.2.1 with php 8.0.8

**Comment by AJITPRASADDIXIT** [comment]
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string & int in E:\atkcovid\vendor\sintattica\atk\src\Core\Tools.php:144
Stack trace:
#0 E:\atkcovid\vendor\sintattica\atk\src\Core\Tools.php(174): Sintattica\Atk\Core\Tools::atkErrorHandler()
#1 [internal function]: Sintattica\Atk\Core\Tools::atkExceptionHandler()
#2 {main}
  thrown in E:\atkcovid\vendor\sintattica\atk\src\Core\Tools.php on line 144
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in E:\atkcovid\vendor\sintattica\atk\src\Utils\Debugger.php:488
Stack trace:
#0 E:\atkcovid\vendor\sintattica\atk\src\Utils\Debugger.php(488): implode()
#1 E:\atkcovid\vendor\sintattica\atk\src\Utils\Debugger.php(555): Sintattica\Atk\Utils\Debugger->renderDebugBlock()
#2 E:\atkcovid\vendor\sintattica\atk\src\Ui\Output.php(141): Sintattica\Atk\Utils\Debugger->renderDebugAndErrorMessages()
#3 E:\atkcovid\vendor\sintattica\atk\src\Core\Tools.php(219): Sintattica\Atk\Ui\Output->outputFlush()
#4 E:\atkcovid\vendor\sintattica\atk\src\Core\Tools.php(160): Sintattica\Atk\Core\Tools::atkhalt()
#5 E:\atkcovid\vendor\sintattica\atk\src\Core\Tools.php(185): Sintattica\Atk\Core\Tools::atkErrorHandler()
#6 [internal function]: Sintattica\Atk\Core\Tools::atkFatalHandler()
#7 {main}
  thrown in E:\atkcovid\vendor\sintattica\atk\src\Utils\Debugger.php on line 488

**Comment by Ald1511** [comment]
Can I have installation guidelines on using atk 9.2.1 with phone 8

**Comment by AJITPRASADDIXIT** [comment]
Please read as php 8

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NGjata** [comment]
Hi, 
We haven’t tested it yet with php8.0 (even though we think it should work), right now we’re testing it in production with php7.2. 
If you want we can send you a base project to start with, but we need a couple of days to prepare the package, otherwise if you can send us an example of your code or explain to us what you are trying to do maybe we can check together and understand where the problem is because it doesn’t seem very clear from the error you sent to us. 



Thanks
Team Sintattica
NG

Sintattica Srl
Piazzale Mazzini 8a
Palazzolo sull’Oglio 25036 BS
phone +39 030 7400104

PMI Innovativa
www.sintattica.it

On 27 July 2021 at 06:43:58, AJITPRASADDIXIT ***@***.***) wrote:

Please read as php 8

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AJITPRASADDIXIT** [comment]
Can you please send me base project to start with

**Comment by AJITPRASADDIXIT** [comment]
I am getting following error
PHP Fatal error:  Uncaught Error: Call to a member function free_result() on null in E:\atkcovid\vendor\sintattica\atk\src\Db\Statement\MySqliStatement.php:221
Stack trace:
#0 E:\atkcovid\vendor\sintattica\atk\src\Db\Statement\Statement.php(227): Sintattica\Atk\Db\Statement\MySqliStatement->_reset()
#1 E:\atkcovid\vendor\sintattica\atk\src\Db\Statement\Statement.php(102): Sintattica\Atk\Db\Statement\Statement->close()
#2 [internal function]: Sintattica\Atk\Db\Statement\Statement->__destruct()
#3 {main}
  thrown in E:\atkcovid\vendor\sintattica\atk\src\Db\Statement\MySqliStatement.php on line 221

**Comment by Ald1511** [comment]
Please send me base project to start with

Regards ,

Ajit

**Comment by NGjata** [comment]
Hi, attached to this mail you will find a demo project + db dump. 

1) Create a database and copy the content of this dump on it.
2) Copy the demo project and set your server content root to the public folder of the project.
4) Make a composer install on project root folder.
5) In config/atk.php set at line 44 -> Set the db connection parameters based on your db.

Now you can navigate at http://localhost:port and should see a login page.

You can provide the following login: 
	Username: sintattica
	Password: wypwuwdu

At this point you should be all set. Please note that this works with php 7.2 at the moment (should be good for php 7.4 but we haven’t tested it yet)

Best regards
NG
Team Sintattica

On 3 August 2021 at 17:01:39, Ald1511 ***@***.***) wrote:

Please send me base project to start with

Regards ,

Ajit

Sent from my iPhone

> On 03-Aug-2021, at 10:19 AM, AJITPRASADDIXIT ***@***.***> wrote:
>  
> ﻿
> I am getting following error
> PHP Fatal error: Uncaught Error: Call to a member function free_result() on null in E:\atkcovid\vendor\sintattica\atk\src\Db\Statement\MySqliStatement.php:221
> Stack trace:
> #0 E:\atkcovid\vendor\sintattica\atk\src\Db\Statement\Statement.php(227): Sintattica\Atk\Db\Statement\MySqliStatement->_reset()
> #1 E:\atkcovid\vendor\sintattica\atk\src\Db\Statement\Statement.php(102): Sintattica\Atk\Db\Statement\Statement->close()
> #2 [internal function]: Sintattica\Atk\Db\Statement\Statement->__destruct()
> #3 {main}
> thrown in E:\atkcovid\vendor\sintattica\atk\src\Db\Statement\MySqliStatement.php on line 221
>  
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jgarifuna** [comment]
I don't see the attachment. Can you please resend it or let me know where to find it?

**Comment by NGjata** [comment]
GitHub must have filtered it. 
Download it here: https://we.tl/t-PldvzcABss
NG


On 4 August 2021 at 16:43:36, Nensi Gjata ***@***.***) wrote:

Hi, attached to this mail you will find a demo project + db dump. 

1) Create a database and copy the content of this dump on it.
2) Copy the demo project and set your server content root to the public folder of the project.
4) Make a composer install on project root folder.
5) In config/atk.php set at line 44 -> Set the db connection parameters based on your db.

Now you can navigate at http://localhost:port and should see a login page.

You can provide the following login: 
	Username: sintattica
	Password: wypwuwdu

At this point you should be all set. Please note that this works with php 7.2 at the moment (should be good for php 7.4 but we haven’t tested it yet)

Best regards
NG
Team Sintattica

On 3 August 2021 at 17:01:39, Ald1511 ***@***.***) wrote:

Please send me base project to start with

Regards ,

Ajit

Sent from my iPhone

> On 03-Aug-2021, at 10:19 AM, AJITPRASADDIXIT ***@***.***> wrote:
>  
> ﻿
> I am getting following error
> PHP Fatal error: Uncaught Error: Call to a member function free_result() on null in E:\atkcovid\vendor\sintattica\atk\src\Db\Statement\MySqliStatement.php:221
> Stack trace:
> #0 E:\atkcovid\vendor\sintattica\atk\src\Db\Statement\Statement.php(227): Sintattica\Atk\Db\Statement\MySqliStatement->_reset()
> #1 E:\atkcovid\vendor\sintattica\atk\src\Db\Statement\Statement.php(102): Sintattica\Atk\Db\Statement\Statement->close()
> #2 [internal function]: Sintattica\Atk\Db\Statement\Statement->__destruct()
> #3 {main}
> thrown in E:\atkcovid\vendor\sintattica\atk\src\Db\Statement\MySqliStatement.php on line 221
>  
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AJITPRASADDIXIT** [comment]
I am getting error in Step 4

**Comment by AJITPRASADDIXIT** [comment]
Can you please guide how to setup under alias setting
In using IIS
My url is http://localhost/atkdemo/
How can I make setup where I get proper theme

Regards ,

Ajit

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Ald1511** [comment]
I want guidance how to configure the theme for ark demo

I am able to install demo and work with demo but not able to get the theme set

I am running on IIS and php 7.2

My url is atkdemo.localhost 

Please guide
